### ISSUE TITLE
'kvm version too old' error

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [intel/Igvtg-kernel#1]
I have compiled/booted the kernel and qemu as described in the IGVT-g_Setup_Guide.txt
However, if I run to test if qemu/kvm works with following command:
# /usr/bin/qemu-system-x86_64 -m 2048 -smp 2 -enable-kvm

it returns:
(process:4468): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
kvm version too old
failed to initialize KVM: Invalid argument

What did I do wrong?

My system: Manjaro(Archlinux)

**Comment by maqiangddb** [comment]
I have this issue too. My system: Centos 7

**Comment by maqiangddb** [comment]
Seems the kvm version depends by igvtg-qemu is different of the kvm version provided by igvtg-kernel. The file ' kvm.h ' is different.

**Comment by l1viathan** [comment]
the missing code was added, please run git fetch and git reset --hard to the new ref.

**Comment by l1viathan** [comment]
I'm going to close this issue.
